[platformio]
src_dir = .

[env:esp32-c3-devkitm-1]
platform = espressif32@6.13.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; Dependencies
lib_deps =
    ArduinoJson@^6.21.0

; Build options
build_flags =
    -D CONFIG_FREERTOS_HZ=1000
    -D CORE_DEBUG_LEVEL=0
    -D CONFIG_TINYUSB_HID_ENABLED=1
    -IC:\\Users\\thoma\\.platformio\\packages\\framework-arduinoespressif32\\tools\\sdk\\esp32s3\\include\\arduino_tinyusb\\tinyusb\\src

; Upload options
upload_speed = 460800
upload_port = COM3

